# Generated by Django 4.1.1 on 2022-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailid',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
